"""Domain layer: core models, value objects, and domain events.

This layer contains pure domain concepts with no I/O, no framework
coupling, and no dependency on engine or systems. All other layers
may depend on domain; domain depends on nothing inside Civitas Lab.
"""

from __future__ import annotations

from civitas.domain.actions import (
    ACTION_CATALOG,
    ACTION_NEED_TARGET,
    ACTION_RESOURCE,
    ActionChoice,
    ActionKind,
)
from civitas.domain.agent import Agent, AgentIdentity
from civitas.domain.birth import (
    DEFAULT_MIN_ENERGY,
    DEFAULT_MIN_FOOD,
    DEFAULT_MIN_PARENT_AGE_TICKS,
    DEFAULT_MIN_WATER,
    DEFAULT_PARENT_ENERGY_COST,
    DEFAULT_PERSONALITY_REGRESSION,
    agent_age_ticks,
    apply_birth,
    can_birth,
    inherit_personality,
)
from civitas.domain.attributes import (
    AgentStatus,
    Belief,
    Beliefs,
    Goal,
    GoalSet,
    Health,
    Inventory,
    Knowledge,
    Memory,
    MemoryRecord,
    Needs,
    Personality,
    Relationship,
    RelationshipMap,
    ResourceStack,
    Skill,
    Skills,
)
from civitas.domain.config import CANONICAL_SEED, SimulationConfig
from civitas.domain.energy import (
    DEFAULT_REST_RESTORE,
    apply_rest,
    can_rest,
    spend_energy,
)
from civitas.domain.events import (
    ActionCompleted,
    ActionSelected,
    AgentBorn,
    AgentMoved,
    AgentSpawned,
    DomainEvent,
    LocationCreated,
    NeedDecayed,
    PopulationObserved,
    ResourceConsumed,
    ResourceGathered,
    SimulationCompleted,
    SimulationStarted,
    TickCompleted,
    TickStarted,
    event_from_record,
)
from civitas.domain.food import (
    DEFAULT_EAT_CONSUME_AMOUNT,
    DEFAULT_EAT_RESTORE,
    FOOD_RESOURCE,
    apply_eat,
    can_eat,
)
from civitas.domain.geography import (
    DEFAULT_MOVE_ENERGY_COST,
    adjacent_locations,
    can_enter,
    enterable_neighbors,
    is_adjacent,
    occupancy,
    relocate,
)
from civitas.domain.ids import AgentId, LocationId
from civitas.domain.location import (
    CAMP_LOCATION,
    Coordinates,
    Location,
    LocationKind,
    default_world_map,
)
from civitas.domain.numeric import clamp_unit
from civitas.domain.population import (
    LocationOccupancy,
    PopulationCensus,
    census,
    location_density,
    next_agent_id,
    population_alive,
    population_dead,
    population_total,
)
from civitas.domain.resources import (
    DEFAULT_GATHER_AMOUNT,
    DEFAULT_INITIAL_STOCK,
    LOCATION_RESOURCE_KINDS,
    RESOURCE_NEED,
    ResourceKind,
    apply_gather,
    deposits_for_kind,
    gatherable_resources,
    location_stock,
    with_deposit_quantity,
)
from civitas.domain.time import Tick
from civitas.domain.water import (
    DEFAULT_DRINK_CONSUME_AMOUNT,
    DEFAULT_DRINK_RESTORE,
    WATER_RESOURCE,
    apply_drink,
    can_drink,
)
from civitas.domain.world import World

__all__ = [
    "ACTION_CATALOG",
    "ACTION_NEED_TARGET",
    "ACTION_RESOURCE",
    "CAMP_LOCATION",
    "CANONICAL_SEED",
    "DEFAULT_DRINK_CONSUME_AMOUNT",
    "DEFAULT_DRINK_RESTORE",
    "DEFAULT_EAT_CONSUME_AMOUNT",
    "DEFAULT_EAT_RESTORE",
    "DEFAULT_GATHER_AMOUNT",
    "DEFAULT_INITIAL_STOCK",
    "DEFAULT_MIN_ENERGY",
    "DEFAULT_MIN_FOOD",
    "DEFAULT_MIN_PARENT_AGE_TICKS",
    "DEFAULT_MIN_WATER",
    "DEFAULT_MOVE_ENERGY_COST",
    "DEFAULT_PARENT_ENERGY_COST",
    "DEFAULT_PERSONALITY_REGRESSION",
    "DEFAULT_REST_RESTORE",
    "FOOD_RESOURCE",
    "LOCATION_RESOURCE_KINDS",
    "RESOURCE_NEED",
    "WATER_RESOURCE",
    "ActionChoice",
    "ActionCompleted",
    "ActionKind",
    "ActionSelected",
    "Agent",
    "AgentBorn",
    "AgentId",
    "AgentIdentity",
    "AgentMoved",
    "AgentSpawned",
    "AgentStatus",
    "Belief",
    "Beliefs",
    "Coordinates",
    "DomainEvent",
    "Goal",
    "GoalSet",
    "Health",
    "Inventory",
    "Knowledge",
    "Location",
    "LocationCreated",
    "LocationId",
    "LocationKind",
    "LocationOccupancy",
    "Memory",
    "MemoryRecord",
    "NeedDecayed",
    "Needs",
    "Personality",
    "PopulationCensus",
    "PopulationObserved",
    "Relationship",
    "RelationshipMap",
    "ResourceConsumed",
    "ResourceGathered",
    "ResourceKind",
    "ResourceStack",
    "SimulationCompleted",
    "SimulationConfig",
    "SimulationStarted",
    "Skill",
    "Skills",
    "Tick",
    "TickCompleted",
    "TickStarted",
    "World",
    "adjacent_locations",
    "agent_age_ticks",
    "apply_birth",
    "apply_drink",
    "apply_eat",
    "apply_gather",
    "apply_rest",
    "can_birth",
    "can_drink",
    "can_eat",
    "can_enter",
    "can_rest",
    "census",
    "clamp_unit",
    "default_world_map",
    "deposits_for_kind",
    "enterable_neighbors",
    "event_from_record",
    "gatherable_resources",
    "inherit_personality",
    "is_adjacent",
    "location_density",
    "location_stock",
    "next_agent_id",
    "occupancy",
    "population_alive",
    "population_dead",
    "population_total",
    "relocate",
    "spend_energy",
    "with_deposit_quantity",
]
