"""Domain layer: core models, value objects, and domain events.

This layer contains pure domain concepts with no I/O, no framework
coupling, and no dependency on engine or systems. All other layers
may depend on domain; domain depends on nothing inside Civitas Lab.
"""

from __future__ import annotations

from civitas.domain.actions import (
    ACTION_CATALOG,
    ACTION_NEED_TARGET,
    ACTION_RESOURCE,
    ActionChoice,
    ActionKind,
)
from civitas.domain.agent import Agent, AgentIdentity
from civitas.domain.attributes import (
    AgentStatus,
    Belief,
    Beliefs,
    Goal,
    GoalSet,
    Health,
    Inventory,
    Knowledge,
    Memory,
    MemoryRecord,
    Needs,
    Personality,
    Relationship,
    RelationshipMap,
    ResourceStack,
    Skill,
    Skills,
)
from civitas.domain.config import CANONICAL_SEED, SimulationConfig
from civitas.domain.events import (
    ActionCompleted,
    ActionSelected,
    AgentMoved,
    AgentSpawned,
    DomainEvent,
    LocationCreated,
    NeedDecayed,
    ResourceConsumed,
    ResourceGathered,
    SimulationCompleted,
    SimulationStarted,
    TickCompleted,
    TickStarted,
    event_from_record,
)
from civitas.domain.geography import (
    DEFAULT_MOVE_ENERGY_COST,
    adjacent_locations,
    can_enter,
    enterable_neighbors,
    is_adjacent,
    occupancy,
    relocate,
)
from civitas.domain.ids import AgentId, LocationId
from civitas.domain.location import (
    CAMP_LOCATION,
    Coordinates,
    Location,
    LocationKind,
    default_world_map,
)
from civitas.domain.numeric import clamp_unit
from civitas.domain.resources import (
    DEFAULT_GATHER_AMOUNT,
    DEFAULT_INITIAL_STOCK,
    LOCATION_RESOURCE_KINDS,
    RESOURCE_NEED,
    ResourceKind,
    apply_gather,
    deposits_for_kind,
    gatherable_resources,
    location_stock,
    with_deposit_quantity,
)
from civitas.domain.time import Tick
from civitas.domain.world import World

__all__ = [
    "ACTION_CATALOG",
    "ACTION_NEED_TARGET",
    "ACTION_RESOURCE",
    "CAMP_LOCATION",
    "CANONICAL_SEED",
    "DEFAULT_GATHER_AMOUNT",
    "DEFAULT_INITIAL_STOCK",
    "DEFAULT_MOVE_ENERGY_COST",
    "LOCATION_RESOURCE_KINDS",
    "RESOURCE_NEED",
    "ActionChoice",
    "ActionCompleted",
    "ActionKind",
    "ActionSelected",
    "Agent",
    "AgentId",
    "AgentIdentity",
    "AgentMoved",
    "AgentSpawned",
    "AgentStatus",
    "Belief",
    "Beliefs",
    "Coordinates",
    "DomainEvent",
    "Goal",
    "GoalSet",
    "Health",
    "Inventory",
    "Knowledge",
    "Location",
    "LocationCreated",
    "LocationId",
    "LocationKind",
    "Memory",
    "MemoryRecord",
    "NeedDecayed",
    "Needs",
    "Personality",
    "Relationship",
    "RelationshipMap",
    "ResourceConsumed",
    "ResourceGathered",
    "ResourceKind",
    "ResourceStack",
    "SimulationCompleted",
    "SimulationConfig",
    "SimulationStarted",
    "Skill",
    "Skills",
    "Tick",
    "TickCompleted",
    "TickStarted",
    "World",
    "adjacent_locations",
    "apply_gather",
    "can_enter",
    "clamp_unit",
    "default_world_map",
    "deposits_for_kind",
    "enterable_neighbors",
    "event_from_record",
    "gatherable_resources",
    "is_adjacent",
    "location_stock",
    "occupancy",
    "relocate",
    "with_deposit_quantity",
]
